from __future__ import annotations

import json
import os
import shlex
import stat
import tempfile
from pathlib import Path


WRAPPER_COMMANDS = (
    ("codex-host-telemetry", "telemetry"),
    ("codex-reclaim-lean", "reclaim"),
)
RULES_FILENAME = "creme-host-capabilities.rules"


def codex_home() -> Path:
    configured = os.environ.get("CODEX_HOME")
    return Path(configured).expanduser() if configured else Path.home() / ".codex"


def default_output_dir() -> Path:
    return codex_home() / "bin"


def default_rules_dir() -> Path:
    return codex_home() / "rules"


def _quoted_rule_token(value: Path | str) -> str:
    return json.dumps(str(value), ensure_ascii=False)


def _telemetry_wrapper(launcher: Path) -> str:
    return (
        "#!/bin/sh\n"
        "set -eu\n"
        "if [ \"$#\" -ne 0 ]; then\n"
        "  echo 'REFUSED — codex-host-telemetry accepts no arguments' >&2\n"
        "  exit 2\n"
        "fi\n"
        f"exec {shlex.quote(str(launcher))} telemetry\n"
    )


def _reclaim_wrapper(launcher: Path) -> str:
    return (
        "#!/bin/sh\n"
        "set -eu\n"
        "case \"${1-}\" in\n"
        "  --dry-run)\n"
        "    [ \"$#\" -eq 1 ] || {\n"
        "      echo 'REFUSED — --dry-run accepts no further arguments' >&2\n"
        "      exit 2\n"
        "    }\n"
        "    ;;\n"
        "  --wind-down)\n"
        "    [ \"$#\" -eq 2 ] || {\n"
        "      echo 'REFUSED — --wind-down requires exactly one goal' >&2\n"
        "      exit 2\n"
        "    }\n"
        "    case \"$2\" in\n"
        "      ''|*[!A-Za-z0-9._-]*)\n"
        "        echo 'REFUSED — invalid goal label' >&2\n"
        "        exit 2\n"
        "        ;;\n"
        "    esac\n"
        "    ;;\n"
        "  *)\n"
        "    echo 'REFUSED — use exactly --dry-run or --wind-down GOAL' >&2\n"
        "    exit 2\n"
        "    ;;\n"
        "esac\n"
        f"exec {shlex.quote(str(launcher))} reclaim \"$@\"\n"
    )


def render_host_wrappers(creme_root: Path) -> dict[str, str]:
    launcher = creme_root.resolve() / "scripts" / "creme"
    return {
        "codex-host-telemetry": _telemetry_wrapper(launcher),
        "codex-reclaim-lean": _reclaim_wrapper(launcher),
    }


def render_host_rules(output_dir: Path) -> str:
    telemetry = output_dir / "codex-host-telemetry"
    reclaim = output_dir / "codex-reclaim-lean"
    telemetry_token = _quoted_rule_token(telemetry)
    reclaim_token = _quoted_rule_token(reclaim)
    telemetry_command = shlex.quote(str(telemetry))
    reclaim_command = shlex.quote(str(reclaim))
    return (
        "# Generated by `python3 -m creme host-wrappers`; review before installing.\n"
        "# Codex loads rules at process startup. Restart Codex after replacement.\n\n"
        "prefix_rule(\n"
        f"    pattern=[{telemetry_token}],\n"
        "    decision=\"allow\",\n"
        "    justification=\"Read-only host telemetry through Creme's argument-rejecting delegate.\",\n"
        f"    match=[{json.dumps(telemetry_command)}],\n"
        f"    not_match=[{json.dumps('/tmp/codex-host-telemetry')}],\n"
        ")\n\n"
        "prefix_rule(\n"
        f"    pattern=[{reclaim_token}, \"--dry-run\"],\n"
        "    decision=\"allow\",\n"
        "    justification=\"Read-only ownership analysis through Creme's constrained delegate.\",\n"
        f"    match=[{json.dumps(reclaim_command + ' --dry-run')}],\n"
        "    not_match=[\n"
        f"        {json.dumps(reclaim_command)},\n"
        f"        {json.dumps(reclaim_command + ' --hard-pressure')},\n"
        f"        {json.dumps(reclaim_command + ' --idle-workers 30 --goal example')},\n"
        "    ],\n"
        ")\n\n"
        "prefix_rule(\n"
        f"    pattern=[{reclaim_token}, \"--wind-down\"],\n"
        "    decision=\"allow\",\n"
        "    justification=\"Goal-scoped ownership-verifying wind-down through Creme's constrained delegate.\",\n"
        f"    match=[{json.dumps(reclaim_command + ' --wind-down example-goal')}],\n"
        "    not_match=[\n"
        f"        {json.dumps(reclaim_command)},\n"
        f"        {json.dumps(reclaim_command + ' --dry-run')},\n"
        f"        {json.dumps(reclaim_command + ' --hard-pressure')},\n"
        "    ],\n"
        ")\n"
    )


def _lexists(path: Path) -> bool:
    return os.path.lexists(path)


def _is_relative_to(path: Path, parent: Path) -> bool:
    try:
        path.relative_to(parent)
    except ValueError:
        return False
    return True


def _validate_destination(directory: Path, expected_parent: Path) -> None:
    if not directory.is_absolute():
        raise ValueError(f"install destination must be absolute: {directory}")
    resolved_parent = expected_parent.expanduser().resolve()
    resolved = directory.expanduser().resolve()
    if not _is_relative_to(resolved, resolved_parent):
        raise ValueError(
            f"install destination must remain under active CODEX_HOME {resolved_parent}: {directory}"
        )
    current = directory
    while not _lexists(current):
        if current == current.parent:
            break
        current = current.parent
    if current.is_symlink():
        raise ValueError(f"install destination has a symbolic-link ancestor: {current}")
    if current.exists():
        mode = stat.S_IMODE(current.stat().st_mode)
        if mode & 0o022:
            raise PermissionError(
                f"install destination ancestor is group/other writable: {current} ({mode:04o})"
            )


def _check_replace_targets(targets: list[Path], replace: bool) -> None:
    blockers = [path for path in targets if _lexists(path)]
    if blockers and not replace:
        joined = ", ".join(str(path) for path in blockers)
        raise FileExistsError(f"bundle output exists: {joined}; use --replace after review")
    invalid = [
        path for path in blockers
        if path.is_symlink() or not path.is_file()
    ]
    if invalid:
        joined = ", ".join(str(path) for path in invalid)
        raise OSError(f"refusing to replace linked or non-regular bundle paths: {joined}")


def _stage(path: Path, content: str, mode: int) -> Path:
    descriptor, temporary = tempfile.mkstemp(
        prefix=f".{path.name}.tmp.", dir=str(path.parent), text=True,
    )
    temporary_path = Path(temporary)
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8") as handle:
            os.fchmod(handle.fileno(), mode)
            handle.write(content)
            handle.flush()
            os.fsync(handle.fileno())
    except BaseException:
        temporary_path.unlink(missing_ok=True)
        raise
    return temporary_path


def install_host_bundle(
    creme_root: Path,
    output_dir: Path,
    rules_dir: Path,
    *,
    replace: bool,
) -> list[Path]:
    expected_home = codex_home()
    _validate_destination(output_dir, expected_home)
    _validate_destination(rules_dir, expected_home)
    if output_dir.resolve() == rules_dir.resolve():
        raise ValueError("wrapper and rules destinations must be different directories")

    wrappers = render_host_wrappers(creme_root)
    rule_path = rules_dir / RULES_FILENAME
    wrapper_paths = [output_dir / name for name in wrappers]
    targets = [*wrapper_paths, rule_path]
    _check_replace_targets(targets, replace)

    output_dir.mkdir(parents=True, exist_ok=True, mode=0o700)
    rules_dir.mkdir(parents=True, exist_ok=True, mode=0o700)
    if not output_dir.is_dir() or output_dir.is_symlink():
        raise NotADirectoryError(f"wrapper output is not a regular directory: {output_dir}")
    if not rules_dir.is_dir() or rules_dir.is_symlink():
        raise NotADirectoryError(f"rules output is not a regular directory: {rules_dir}")

    staged: list[tuple[Path, Path]] = []
    try:
        for name, content in wrappers.items():
            target = output_dir / name
            staged.append((target, _stage(target, content, 0o700)))
        staged.append((rule_path, _stage(rule_path, render_host_rules(output_dir), 0o600)))

        # Publish authorization last. An interrupted first install therefore
        # leaves delegates that still prompt, rather than a rule pointing at a
        # missing or half-written executable.
        for target, temporary_path in staged:
            os.replace(temporary_path, target)
        return targets
    finally:
        for _, temporary_path in staged:
            temporary_path.unlink(missing_ok=True)


def install_host_wrappers(
    creme_root: Path,
    output_dir: Path,
    *,
    replace: bool,
) -> list[Path]:
    """Compatibility entry point for callers that explicitly install wrappers only.

    New callers must use :func:`install_host_bundle`; leaving this helper
    available keeps imports stable while making wrapper-only installation fail
    closed instead of silently recreating the authorization regression.
    """
    raise RuntimeError(
        "wrapper-only installation is retired; install_host_bundle requires a rules directory"
    )


def _installed_file_issues(path: Path, expected: str, mode: int) -> list[str]:
    if not _lexists(path):
        return [f"{path.name}: missing"]
    if path.is_symlink():
        return [f"{path.name}: symbolic link"]
    if not path.is_file():
        return [f"{path.name}: not a regular file"]
    issues: list[str] = []
    try:
        actual = path.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError) as exc:
        return [f"{path.name}: unreadable ({exc})"]
    if actual != expected:
        issues.append(f"{path.name}: content mismatch")
    actual_mode = stat.S_IMODE(path.stat().st_mode)
    if actual_mode != mode:
        issues.append(
            f"{path.name}: mode {actual_mode:04o}, expected {mode:04o}"
        )
    if path.stat().st_uid != os.getuid():
        issues.append(f"{path.name}: not owned by the current user")
    return issues


def bundle_install_issues(
    creme_root: Path,
    output_dir: Path,
    rules_dir: Path,
) -> list[str]:
    wrappers = render_host_wrappers(creme_root)
    issues: list[str] = []
    for name, expected in wrappers.items():
        issues.extend(_installed_file_issues(output_dir / name, expected, 0o700))
    issues.extend(_installed_file_issues(
        rules_dir / RULES_FILENAME, render_host_rules(output_dir), 0o600,
    ))
    return issues


def wrapper_install_issues(
    creme_root: Path,
    output_dir: Path,
) -> list[str]:
    """Compatibility check that now reports the complete default bundle."""
    return bundle_install_issues(creme_root, output_dir, default_rules_dir())
